apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-downloader-deployment
spec:
  replicas: 2  # Certifique-se de que há 2 réplicas
  selector:
    matchLabels:
      app: pdf-downloader
  template:
    metadata:
      labels:
        app: pdf-downloader
    spec:
      containers:
      - name: pdf-downloader
        image: pdf-downloader-image:latest  # Imagem correta
        imagePullPolicy: IfNotPresent  # Melhor usar 'IfNotPresent' para evitar o download repetido
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: pdf-storage
          mountPath: /app/downloads
      volumes:
      - name: pdf-storage
        emptyDir: {}
