apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-downloader-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-downloader-deployment  # Certifique-se de usar o nome correto do seu Deployment
  minReplicas: 2  # Número mínimo de réplicas
  maxReplicas: 5  # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # O HPA tentará manter a utilização da CPU em 50%
