apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics-nodeport
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
    - name: http
      port: 8080                # Porta interna do serviço
      targetPort: 8080           # Porta onde o kube-state-metrics está ouvindo
      nodePort: 31000            # Porta exposta no nó
