apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Nome do role
  # Pode ser nomeado como "system:metrics-server"
  # ou outro nome se necessário
  name: system:metrics-server
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list"]